import { alertLayout } from "../shared/alertLayout.js";
import {
  detailRow,
  detailsBox,
  bulletBox,
  mapImageBlock,
  recipientsList,
  actionButton,
} from "../shared/components.js";
import { STATUS_THEME, BRAND } from "../shared/theme.js";

/**
 * Active SOS alert — sent to each trusted contact / campus security when a
 * user triggers an emergency alert.
 */
export function sosAlertEmailTemplate({
  recipientName,
  userName,
  userPhone,
  userEmail,
  latitude,
  longitude,
  locationLink,
  locationLabel,
  contacts = [],
  alertId,
  timestamp,
  message,
  googleMapsApiKey,
  campusSecurityPhone,
}) {
  const theme = STATUS_THEME.active;
  const displayName = userName || userPhone || "A user";
  const hasMessage = message && message.length > 0;

  const getMessagePreview = (msg) => {
    if (!msg) return "";
    const truncated = msg.length > 30 ? `${msg.substring(0, 30)}...` : msg;
    return ` - "${truncated}"`;
  };

  const subject = `🚨 SOS Alert from ${displayName}${getMessagePreview(message)}`;

  const locationUrl =
    locationLink ||
    (typeof latitude === "number" && typeof longitude === "number"
      ? `https://www.google.com/maps?q=${latitude},${longitude}`
      : null);

  const detailsRows =
    detailRow("Time Triggered:", timestamp || new Date().toLocaleString()) +
    detailRow(
      "Last Known Location:",
      locationLabel ? `📍 ${locationLabel}` : null,
    ) +
    detailRow("Phone:", userPhone) +
    detailRow("Email:", userEmail, { last: true });

  const bodyHtml = `
    <p class="greeting">Hi ${recipientName || "there"},</p>
    <p class="lead">${displayName} has triggered an SOS alert via ${BRAND.name} and listed you as an emergency contact. They may require immediate assistance.</p>

    ${
      hasMessage
        ? `<h4 class="section-heading">Message</h4>
           <div class="message-quote">"${message}"</div>
           <p class="message-caption">This message was automatically generated by ${BRAND.name} when ${displayName} activated an SOS alert.</p>`
        : ""
    }

    ${bulletBox({
      title: "Immediate Actions Required:",
      ordered: true,
      boxBg: theme.boxBg,
      boxText: theme.boxText,
      items: [
        `Attempt to contact ${displayName} immediately via phone or text`,
        "Review their live location and route details using the link below.",
        `If you cannot reach them and believe they are in immediate danger, contact Campus Security${campusSecurityPhone ? " at " + campusSecurityPhone : ""} or local emergency authorities.`,
      ],
    })}

    <h4 class="section-heading">Alert Details</h4>
    ${detailsBox(null, detailsRows)}

    <h4 class="section-heading">Live Location</h4>
    ${mapImageBlock({ latitude, longitude, googleMapsApiKey })}
    ${locationUrl ? `<div style="text-align:center;">${actionButton(locationUrl, "Open Live Location", { bg: theme.buttonBg })}</div>` : ""}

    ${recipientsList(contacts)}
  `;

  const html = alertLayout({
    headerBg: theme.headerBg,
    headerIcon: "🚨",
    headerTitle: "SOS EMERGENCY ALERT",
    headerSubtitle: "Immediate attention required",
    pillLabel: "EMERGENCY ALERT TRIGGERED",
    pillBg: theme.pillBg,
    pillText: theme.pillText,
    bodyHtml,
    extraCSS: `.section-heading { margin: 22px 0 8px; color: #333; font-size: 15px; }`,
  });

  const text = `
🚨 SOS EMERGENCY ALERT
Immediate attention required

Hi ${recipientName || "there"},

${displayName} has triggered an SOS alert via ${BRAND.name} and listed you as an emergency contact. They may require immediate assistance.
${hasMessage ? `\nMessage: "${message}"\n` : ""}
Time Triggered: ${timestamp || new Date().toLocaleString()}
${locationLabel ? `Last Known Location: ${locationLabel}` : ""}
${userPhone ? `Phone: ${userPhone}` : ""}
${userEmail ? `Email: ${userEmail}` : ""}

Location: ${locationUrl || "Location not available"}

This alert was sent to:
${contacts.map((c) => `- ${c.name} (${c.relationship || c.type || "Contact"})`).join("\n")}

⚠️ If this is a false alarm, ${displayName} can cancel it from the app.

---
${BRAND.name} - Emergency Alert System
Alert ID: ${alertId || "N/A"}
This is an automated message. Please do not reply.
  `.trim();

  return { subject, html, text };
}
